from ..Classes.Variabele import Variabele
from ..Classes..VariableInstance import VariableInstance
from ..Classes..VariableInstanceWithResourceValue import VariableInstanceWithResourceValue
from ..Classes..VariableWithLiteralValue import VariableWithLiteralValue
from ..Classes.Agent import Agent
from ..Classes.isPartOf import isPartOf
from ..Classes.isOntwerpVoor import isOntwerpVoor
from ..Classes.Concept import Concept
from ..Classes.wasDerivedFrom import wasDerivedFrom
from ..Classes.Besluit.AanvullendReglement import AanvullendReglement
from ..Classes.Besluit.Artikel import Artikel
from ..Classes.Besluit.Besluit import Besluit
from ..Classes.Besluit.Voorwaarde import Voorwaarde
from ..Classes.Besluit.heeftVoorwaarde import heeftVoorwaarde
from ..Classes.Mobiliteit.AanvullendReglementOntwerp import AanvullendReglementOntwerp
from ..Classes.Mobiliteit.AanvullendReglementOntwerp.heeftOntwerp import AanvullendReglementOntwerp.heeftOntwerp
from ..Classes.Mobiliteit.Artikel.heeftMobiliteitsmaatregel import Artikel.heeftMobiliteitsmaatregel
from ..Classes.Mobiliteit.MaatregelVerkeerstekenLijstItem import MaatregelVerkeerstekenLijstItem
from ..Classes.Mobiliteit.MaatregelVerkeerstekenLijstItem.heeftVerkeerstekenLijstItem import MaatregelVerkeerstekenLijstItem.heeftVerkeerstekenLijstItem
from ..Classes.Mobiliteit.Mobiliteitsmaatregel import Mobiliteitsmaatregel
from ..Classes.Mobiliteit.Mobiliteitsmaatregel.verwijdertMaatregel import Mobiliteitsmaatregel.verwijdertMaatregel
from ..Classes.Mobiliteit.Mobiliteitsmaatregelconcept import Mobiliteitsmaatregelconcept
from ..Classes.Mobiliteit.Mobiliteitsmaatregelconcept.heeftMaatregelconcept import Mobiliteitsmaatregelconcept.heeftMaatregelconcept
from ..Classes.Mobiliteit.MobliteitsmaatregelOntwerp import MobliteitsmaatregelOntwerp
from ..Classes.Mobiliteit.OntwerpVerkeersteken import OntwerpVerkeersteken
from ..Classes.Mobiliteit.Pictogram import Pictogram
from ..Classes.Mobiliteit.SignalisatieOntwerp import SignalisatieOntwerp
from ..Classes.Mobiliteit.Variabele.heeftWaardeVoor import Variabele.heeftWaardeVoor
from ..Classes.Mobiliteit.VariabeleInstantieMetLocatie import VariabeleInstantieMetLocatie
from ..Classes.Mobiliteit.VariabeleMetLocatie import VariabeleMetLocatie
from ..Classes.Mobiliteit.VariabeleMetVerwijzing import VariabeleMetVerwijzing
from ..Classes.Mobiliteit.VerkeersbordVerkeersteken import VerkeersbordVerkeersteken
from ..Classes.Mobiliteit.Verkeersbordconcept import Verkeersbordconcept
from ..Classes.Mobiliteit.VerkeerslichtVerkeersteken import VerkeerslichtVerkeersteken
from ..Classes.Mobiliteit.Verkeerslichtconcept import Verkeerslichtconcept
from ..Classes.Mobiliteit.Verkeersteken import Verkeersteken
from ..Classes.Mobiliteit.Verkeersteken.bevatVerkeersteken import Verkeersteken.bevatVerkeersteken
from ..Classes.Mobiliteit.Verkeerstekenconcept import Verkeerstekenconcept
from ..Classes.Mobiliteit.Verkeerstekenconcept.definieert import Verkeerstekenconcept.definieert
from ..Classes.Mobiliteit.Verkeerstekenconcept.heeftStandaardVorm import Verkeerstekenconcept.heeftStandaardVorm
from ..Classes.Mobiliteit.WegmarkeringVerkeersteken import WegmarkeringVerkeersteken
from ..Classes.Mobiliteit.Wegmarkeringsconcept import Wegmarkeringsconcept
from ..Classes.DtcZone import DtcZone
from ..Classes.Mobiliteit.heeftGerelateerdVerkeersteken import heeftGerelateerdVerkeersteken
from ..Classes.Mobiliteit.heeftMogelijkOnderbord import heeftMogelijkOnderbord
from ..Classes.Mobiliteit.heeftOnderbord import heeftOnderbord
from ..Classes.Mobiliteit.wordtAangeduidDoor import wordtAangeduidDoor
from ..Classes.bevatMaatregelOntwerp import bevatMaatregelOntwerp
from ..Classes.bevatOntwerp import bevatOntwerp
from ..Classes.bevatOntwerpVoor import bevatOntwerpVoor
from ..Classes.heeftItem import heeftItem
from ..Classes.heeftVerkeersteken import heeftVerkeersteken
from ..Classes.ontwerpVanMaatregel import ontwerpVanMaatregel
from ..Classes..VariableInstanceWithLiteralValue import VariableInstanceWithLiteralValue
from ..Classes.isCharacterisedBy import isCharacterisedBy
from ..Classes.DtcVorm import DtcVorm
from ..Classes.ImplementatieElement.Derdenobject import Derdenobject
from ..Classes.ImplementatieElement.Toegangsprocedure import Toegangsprocedure
from ..Classes.Installatie.AanzichtVerkeersbordopstelling import AanzichtVerkeersbordopstelling
from ..Classes.Installatie.Verkeersbordopstelling import Verkeersbordopstelling
from ..Classes.Onderdeel.AanvullendeGeometrie import AanvullendeGeometrie
from ..Classes.Onderdeel.Bevestiging import Bevestiging
from ..Classes.Onderdeel.Bijlage import Bijlage
from ..Classes.Onderdeel.HeeftAanvullendeGeometrie import HeeftAanvullendeGeometrie
from ..Classes.Onderdeel.HeeftAanzicht import HeeftAanzicht
from ..Classes.Onderdeel.HeeftBetrokkene import HeeftBetrokkene
from ..Classes.Onderdeel.HeeftBijlage import HeeftBijlage
from ..Classes.Onderdeel.HeeftNetwerkProtectie import HeeftNetwerkProtectie
from ..Classes.Onderdeel.HeeftNetwerktoegang import HeeftNetwerktoegang
from ..Classes.Onderdeel.HeeftToegangsprocedure import HeeftToegangsprocedure
from ..Classes.Onderdeel.HoortBij import HoortBij
from ..Classes.Onderdeel.IsAdmOnderdeelVan import IsAdmOnderdeelVan
from ..Classes.Onderdeel.IsInspectieVan import IsInspectieVan
from ..Classes.Onderdeel.IsNetwerkECC import IsNetwerkECC
from ..Classes.Onderdeel.IsOntwerpVan import IsOntwerpVan
from ..Classes.Onderdeel.IsSWGehostOp import IsSWGehostOp
from ..Classes.Onderdeel.IsSWOnderdeelVan import IsSWOnderdeelVan
from ..Classes.Onderdeel.LigtOp import LigtOp
from ..Classes.Onderdeel.Omhult import Omhult
from ..Classes.Onderdeel.Realiseert import Realiseert
from ..Classes.Onderdeel.RetroreflecterendVerkeersbord import RetroreflecterendVerkeersbord
from ..Classes.Onderdeel.RetroreflecterendeFolie import RetroreflecterendeFolie
from ..Classes.Onderdeel.SluitAanOp import SluitAanOp
from ..Classes.Onderdeel.Sturing import Sturing
from ..Classes.Onderdeel.Voedt import Voedt
from ..Classes.Onderdeel.VoedtAangestuurd import VoedtAangestuurd
from ..Classes.Codelijst import Codelijst
from ..Classes.inScheme import inScheme
from ..Classes.Legacy.IRVerlichter import IRVerlichter
from ..Classes.Legacy.VKS import VKS
from ..Classes.Legacy.Z30Controller import Z30Controller
from ..Classes.Legacy.CaDoGroep import CaDoGroep
from ..Classes.Legacy.LWP import LWP
from ..Classes.Legacy.HY_CI import HY_CI
from ..Classes.Legacy.HY_GR import HY_GR
from ..Classes.Legacy.Poortbedieningen import Poortbedieningen
from ..Classes.Legacy.MotorLegacy import MotorLegacy
from ..Classes.Legacy.StuurklepLeiding import StuurklepLeiding
from ..Classes.Legacy.FlexibeleBuis import FlexibeleBuis
from ..Classes.Legacy.ZoutBijlaadPlaats import ZoutBijlaadPlaats
from ..Classes.Legacy.ITSApp_RIS import ITSApp_RIS
from ..Classes.Legacy.Zoutsilo import Zoutsilo
from ..Classes.Legacy.Pekeltank import Pekeltank
from ..Classes.Legacy.BelInstallatie import BelInstallatie
from ..Classes.Legacy.RIOOL import RIOOL
from ..Classes.Legacy.LokaalLegacy import LokaalLegacy
from ..Classes.Legacy.Dienstdeur import Dienstdeur
from ..Classes.Legacy.FietsTelDisplayLegacy import FietsTelDisplayLegacy
from ..Classes.Legacy.FietsTelSysteemLegacy import FietsTelSysteemLegacy
from ..Classes.Legacy.DPBS import DPBS
from ..Classes.Legacy.DPBSOnd import DPBSOnd
from ..Classes.Legacy.WegDetectorLegacy import WegDetectorLegacy
from ..Classes.Legacy.SegC import SegC
from ..Classes.Legacy.Netwerktoegang import Netwerktoegang
from ..Classes.Legacy.Turbine import Turbine
from ..Classes.Legacy.WeegsensorLegacy import WeegsensorLegacy
from ..Classes.Legacy.WeegsensorGroep import WeegsensorGroep
from ..Classes.Legacy.Luchtkwaliteitssensor import Luchtkwaliteitssensor
from ..Classes.Legacy.Beacon import Beacon
from ..Classes.Legacy.Leidingkoker import Leidingkoker
from ..Classes.Legacy.SeinBak import SeinBak
from ..Classes.Legacy.SeinSpui import SeinSpui
from ..Classes.Legacy.RLCGUI import RLCGUI
from ..Classes.Legacy.SlbGroep import SlbGroep
from ..Classes.Legacy.Calam import Calam
from ..Classes.Legacy.Glad import Glad
from ..Classes.Legacy.Ijking import Ijking
from ..Classes.Legacy.VOTLus import VOTLus
from ..Classes.Legacy.VVOPGroep import VVOPGroep
from ..Classes.Legacy.Brandvoorz import Brandvoorz
from ..Classes.Legacy.RRGroep import RRGroep
from ..Classes.Legacy.AntenneI2V import AntenneI2V
from ..Classes.Legacy.Monitor import Monitor
from ..Classes.Legacy.LuiLegacy import LuiLegacy
from ..Classes.Legacy.NIC import NIC
from ..Classes.Legacy.Winter import Winter
from ..Classes.Legacy.Z30Paal import Z30Paal
from ..Classes.Legacy.Z30 import Z30
from ..Classes.Legacy.Pluvio import Pluvio
from ..Classes.Legacy.ARS import ARS
from ..Classes.Legacy.RHZ import RHZ
from ..Classes.Legacy.Picto import Picto
from ..Classes.Legacy.Nooddeur import Nooddeur
from ..Classes.Legacy.KeuringLegacy import KeuringLegacy
from ..Classes.Legacy.Deb import Deb
from ..Classes.Legacy.MON import MON
from ..Classes.Legacy.Kwik import Kwik
from ..Classes.Legacy.Div import Div
from ..Classes.Legacy.Peil import Peil
from ..Classes.Legacy.Lev import Lev
from ..Classes.Legacy.Cal import Cal
from ..Classes.Legacy.Sensor import Sensor
from ..Classes.Legacy.GebUitr import GebUitr
from ..Classes.Legacy.GebouwLegacy import GebouwLegacy
from ..Classes.Legacy.ServerGrp import ServerGrp
from ..Classes.Legacy.Server import Server
from ..Classes.Legacy.IVSBGroep import IVSBGroep
from ..Classes.Legacy.SeinbrugIVS import SeinbrugIVS
from ..Classes.Legacy.MDeC import MDeC
from ..Classes.Legacy.Kast import Kast
from ..Classes.Legacy.Wilddet import Wilddet
from ..Classes.Legacy.Terrein import Terrein
from ..Classes.Legacy.Druk import Druk
from ..Classes.Legacy.Wind import Wind
from ..Classes.Legacy.VPBevestig import VPBevestig
from ..Classes.Legacy.VPConsole import VPConsole
from ..Classes.Legacy.KAR import KAR
from ..Classes.Legacy.RRB import RRB
from ..Classes.Legacy.RISLegacy import RISLegacy
from ..Classes.Legacy.Tekstkar import Tekstkar
from ..Classes.Legacy.SoftwareLegacy import SoftwareLegacy
from ..Classes.Legacy.MobADR import MobADR
from ..Classes.Legacy.IP import IP
from ..Classes.Legacy.TWeg import TWeg
from ..Classes.Legacy.VSB import VSB
from ..Classes.Legacy.AWeg import AWeg
from ..Classes.Legacy.NWeg import NWeg
from ..Classes.Legacy.BWeg import BWeg
from ..Classes.Legacy.RWeg import RWeg
from ..Classes.Legacy.VOT import VOT
from ..Classes.Legacy.Instal import Instal
from ..Classes.Legacy.RTU import RTU
from ..Classes.Legacy.Kan import Kan
from ..Classes.Legacy.Com import Com
from ..Classes.Legacy.TTN3 import TTN3
from ..Classes.Legacy.TTN2 import TTN2
from ..Classes.Legacy.TTN1 import TTN1
from ..Classes.Legacy.Dummy import Dummy
from ..Classes.Legacy.TraCoLegacy import TraCoLegacy
from ..Classes.Legacy.WIM import WIM
from ..Classes.Legacy.CBBS import CBBS
from ..Classes.Legacy.VWS import VWS
from ..Classes.Legacy.TGB import TGB
from ..Classes.Legacy.WKD import WKD
from ..Classes.Legacy.BAf import BAf
from ..Classes.Legacy.MVE import MVE
from ..Classes.Legacy.ICU import ICU
from ..Classes.Legacy.VDP import VDP
from ..Classes.Legacy.Veer import Veer
from ..Classes.Legacy.WV import WV
from ..Classes.Legacy.WDM import WDM
from ..Classes.Legacy.WBr import WBr
from ..Classes.Legacy.VVOP import VVOP
from ..Classes.Legacy.VRLegacy import VRLegacy
from ..Classes.Legacy.VL import VL
from ..Classes.Legacy.VGL import VGL
from ..Classes.Legacy.UPSLegacy import UPSLegacy
from ..Classes.Legacy.TuV import TuV
from ..Classes.Legacy.Tu import Tu
from ..Classes.Legacy.TTN import TTN
from ..Classes.Legacy.TT import TT
from ..Classes.Legacy.TGC import TGC
from ..Classes.Legacy.Tel import Tel
from ..Classes.Legacy.TCC import TCC
from ..Classes.Legacy.Str import Str
from ..Classes.Legacy.Stuw import Stuw
from ..Classes.Legacy.Ssig import Ssig
from ..Classes.Legacy.Sluis import Sluis
from ..Classes.Legacy.SDH import SDH
from ..Classes.Legacy.Schuiven import Schuiven
from ..Classes.Legacy.Rooster import Rooster
from ..Classes.Legacy.Ramp import Ramp
from ..Classes.Legacy.Radio import Radio
from ..Classes.Legacy.PTK import PTK
from ..Classes.Legacy.PP import PP
from ..Classes.Legacy.PoS import PoS
from ..Classes.Legacy.NSG import NSG
from ..Classes.Legacy.ModRck import ModRck
from ..Classes.Legacy.Modem import Modem
from ..Classes.Legacy.MobDet import MobDet
from ..Classes.Legacy.Meteo import Meteo
from ..Classes.Legacy.LS import LS
from ..Classes.Legacy.Lift import Lift
from ..Classes.Legacy.KlimaLegacy import KlimaLegacy
from ..Classes.Legacy.Roltrap import Roltrap
from ..Classes.Legacy.Vent import Vent
from ..Classes.Legacy.KL import KL
from ..Classes.Legacy.IVSB import IVSB
from ..Classes.Legacy.Int import Int
from ..Classes.Legacy.HS import HS
from ..Classes.Legacy.HHW import HHW
from ..Classes.Legacy.FCel import FCel
from ..Classes.Legacy.Elc import Elc
from ..Classes.Legacy.Det import Det
from ..Classes.Legacy.CVL import CVL
from ..Classes.Legacy.Slb import Slb
from ..Classes.Legacy.CC import CC
from ..Classes.Legacy.BVE import BVE
from ..Classes.Legacy.Bus import Bus
from ..Classes.Legacy.BeweegbareBrug import BeweegbareBrug
from ..Classes.Legacy.BiF import BiF
from ..Classes.Legacy.BIB import BIB
from ..Classes.Legacy.BDV import BDV
from ..Classes.Legacy.BBT import BBT
from ..Classes.Legacy.ATOS import ATOS
from ..Classes.Legacy.Asw import Asw
from ..Classes.Legacy.Audio import Audio
from ..Classes.Legacy.AfGroep import AfGroep
from ..Classes.Legacy.Af import Af
from ..Classes.Legacy.AB import AB
from ..Classes.Legacy.COD import COD
from ..Classes.Legacy.PLCLegacy import PLCLegacy
from ..Classes.Legacy.Bareel import Bareel
from ..Classes.Legacy.BAFG import BAFG
from ..Classes.Legacy.Poortbediening import Poortbediening
from ..Classes.Legacy.VPLMast import VPLMast
from ..Classes.Legacy.Mpt import Mpt
from ..Classes.Legacy.HPGroep import HPGroep
from ..Classes.Legacy.CaDoLegacy import CaDoLegacy
from ..Classes.Legacy.Buitendeur import Buitendeur
from ..Classes.Legacy.Brandmelder import Brandmelder
from ..Classes.Legacy.ADRBuffer import ADRBuffer
from ..Classes.Legacy.VerbindD import VerbindD
from ..Classes.Legacy.BBLegacy import BBLegacy
from ..Classes.Legacy.HulppostLegacy import HulppostLegacy
from ..Classes.Legacy.Rookmelder import Rookmelder
from ..Classes.Legacy.Astrid import Astrid
from ..Classes.Legacy.BevRelais import BevRelais
from ..Classes.Legacy.DiffRelais import DiffRelais
from ..Classes.Legacy.HSMelder import HSMelder
from ..Classes.Legacy.OvRelais import OvRelais
from ..Classes.Legacy.LVS import LVS
from ..Classes.Legacy.LSBordLegacy import LSBordLegacy
from ..Classes.Legacy.NDVL import NDVL
from ..Classes.Legacy.PompLegacy import PompLegacy
from ..Classes.Legacy.Sstart import Sstart
from ..Classes.Legacy.Vlot import Vlot
from ..Classes.Legacy.SNCPaal import SNCPaal
from ..Classes.Legacy.RLCPaal import RLCPaal
from ..Classes.Legacy.Deurcontact import Deurcontact
from ..Classes.Legacy.ContourVLLegacy import ContourVLLegacy
from ..Classes.Legacy.Beton import Beton
from ..Classes.Legacy.HSDeel import HSDeel
from ..Classes.Legacy.LSDeel import LSDeel
from ..Classes.Legacy.HSCabineLegacy import HSCabineLegacy
from ..Classes.Legacy.OTN import OTN
from ..Classes.Legacy.CEN import CEN
from ..Classes.Legacy.Rijstrook import Rijstrook
from ..Classes.Legacy.Noodstroom import Noodstroom
from ..Classes.Legacy.Beheersys import Beheersys
from ..Classes.Legacy.VC import VC
from ..Classes.Legacy.ADW import ADW
from ..Classes.Legacy.SeinBaan import SeinBaan
from ..Classes.Legacy.SeinRiv import SeinRiv
from ..Classes.Legacy.SeinOnd import SeinOnd
from ..Classes.Legacy.SeinRicht import SeinRicht
from ..Classes.Legacy.SeinSch import SeinSch
from ..Classes.Legacy.SeinbrugRRB import SeinbrugRRB
from ..Classes.Legacy.OmvormerLegacy import OmvormerLegacy
from ..Classes.Legacy.Decoder import Decoder
from ..Classes.Legacy.ADR import ADR
from ..Classes.Legacy.FietstelLegacy import FietstelLegacy
from ..Classes.Legacy.MIVLVE import MIVLVE
from ..Classes.Legacy.CCTVPaal import CCTVPaal
from ..Classes.Legacy.TH import TH
from ..Classes.Legacy.Relais import Relais
from ..Classes.Legacy.MS import MS
from ..Classes.Legacy.Thermo import Thermo
from ..Classes.Legacy.TransfoLegacy import TransfoLegacy
from ..Classes.Legacy.HVS import HVS
from ..Classes.Legacy.Paal import Paal
from ..Classes.Legacy.SeinbrugRR import SeinbrugRR
from ..Classes.Legacy.PKGroep import PKGroep
from ..Classes.Legacy.PK import PK
from ..Classes.Legacy.RSSGroep import RSSGroep
from ..Classes.Legacy.VMSGroep import VMSGroep
from ..Classes.Legacy.RVMSGroep import RVMSGroep
from ..Classes.Legacy.RSSBord import RSSBord
from ..Classes.Legacy.RVMS import RVMS
from ..Classes.Legacy.RRBGroep import RRBGroep
from ..Classes.Legacy.WegPunt import WegPunt
from ..Classes.Legacy.HPicto import HPicto
from ..Classes.Legacy.Switch import Switch
from ..Classes.Legacy.CamGroep import CamGroep
from ..Classes.Legacy.SeinbrugDVM import SeinbrugDVM
from ..Classes.Legacy.MIVSat import MIVSat
from ..Classes.Legacy.PTZ import PTZ
from ..Classes.Legacy.ANPR import ANPR
from ..Classes.Legacy.CCTV import CCTV
from ..Classes.Legacy.AID import AID
from ..Classes.Legacy.Encoder import Encoder
from ..Classes.Legacy.DIZV import DIZV
from ..Classes.Legacy.CameraLegacy import CameraLegacy
from ..Classes.Legacy.RLC import RLC
from ..Classes.Legacy.ANPRPaal import ANPRPaal
from ..Classes.Legacy.SNC import SNC
from ..Classes.Legacy.VMS import VMS
