# coding=utf-8
from ..BaseClasses.KeuzelijstField import KeuzelijstField
from ..BaseClasses.KeuzelijstWaarde import KeuzelijstWaarde


# Generated with OTLEnumerationCreator. To modify: extend, do not edit
class KlTakvrijeHoogte(KeuzelijstField):
    """De mogelijke opties voor de takvrije hoogte in meter."""
    naam = 'KlTakvrijeHoogte'
    label = 'Takvrije hoogte'
    objectUri = 'https://wegenenverkeer.data.vlaanderen.be/ns/onderdeel#KlTakvrijeHoogte'
    definition = 'De mogelijke opties voor de takvrije hoogte in meter.'
    status = 'ingebruik'
    codelist = 'https://wegenenverkeer.data.vlaanderen.be/id/conceptscheme/KlTakvrijeHoogte'
    options = {
        '0': KeuzelijstWaarde(invulwaarde='0',
                              label='0',
                              status='ingebruik',
                              definitie='0',
                              objectUri='https://wegenenverkeer.data.vlaanderen.be/id/concept/KlTakvrijeHoogte/0'),
        '0-5': KeuzelijstWaarde(invulwaarde='0-5',
                                label='0.5',
                                status='ingebruik',
                                definitie='0.5',
                                objectUri='https://wegenenverkeer.data.vlaanderen.be/id/concept/KlTakvrijeHoogte/0-5'),
        '1': KeuzelijstWaarde(invulwaarde='1',
                              label='1',
                              status='ingebruik',
                              definitie='1',
                              objectUri='https://wegenenverkeer.data.vlaanderen.be/id/concept/KlTakvrijeHoogte/1'),
        '1-5': KeuzelijstWaarde(invulwaarde='1-5',
                                label='1.5',
                                status='ingebruik',
                                definitie='1.5',
                                objectUri='https://wegenenverkeer.data.vlaanderen.be/id/concept/KlTakvrijeHoogte/1-5'),
        '10': KeuzelijstWaarde(invulwaarde='10',
                               label='10',
                               status='ingebruik',
                               definitie='10',
                               objectUri='https://wegenenverkeer.data.vlaanderen.be/id/concept/KlTakvrijeHoogte/10'),
        '10-5': KeuzelijstWaarde(invulwaarde='10-5',
                                 label='10.5',
                                 status='ingebruik',
                                 definitie='10.5',
                                 objectUri='https://wegenenverkeer.data.vlaanderen.be/id/concept/KlTakvrijeHoogte/10-5'),
        '11': KeuzelijstWaarde(invulwaarde='11',
                               label='11',
                               status='ingebruik',
                               definitie='11',
                               objectUri='https://wegenenverkeer.data.vlaanderen.be/id/concept/KlTakvrijeHoogte/11'),
        '2': KeuzelijstWaarde(invulwaarde='2',
                              label='2',
                              status='ingebruik',
                              definitie='2',
                              objectUri='https://wegenenverkeer.data.vlaanderen.be/id/concept/KlTakvrijeHoogte/2'),
        '2-5': KeuzelijstWaarde(invulwaarde='2-5',
                                label='2.5',
                                status='ingebruik',
                                definitie='2.5',
                                objectUri='https://wegenenverkeer.data.vlaanderen.be/id/concept/KlTakvrijeHoogte/2-5'),
        '3': KeuzelijstWaarde(invulwaarde='3',
                              label='3',
                              status='ingebruik',
                              definitie='3',
                              objectUri='https://wegenenverkeer.data.vlaanderen.be/id/concept/KlTakvrijeHoogte/3'),
        '3-5': KeuzelijstWaarde(invulwaarde='3-5',
                                label='3.5',
                                status='ingebruik',
                                definitie='3.5',
                                objectUri='https://wegenenverkeer.data.vlaanderen.be/id/concept/KlTakvrijeHoogte/3-5'),
        '4': KeuzelijstWaarde(invulwaarde='4',
                              label='4',
                              status='ingebruik',
                              definitie='4',
                              objectUri='https://wegenenverkeer.data.vlaanderen.be/id/concept/KlTakvrijeHoogte/4'),
        '4-5': KeuzelijstWaarde(invulwaarde='4-5',
                                label='4.5',
                                status='ingebruik',
                                definitie='4.5',
                                objectUri='https://wegenenverkeer.data.vlaanderen.be/id/concept/KlTakvrijeHoogte/4-5'),
        '5': KeuzelijstWaarde(invulwaarde='5',
                              label='5',
                              status='ingebruik',
                              definitie='5',
                              objectUri='https://wegenenverkeer.data.vlaanderen.be/id/concept/KlTakvrijeHoogte/5'),
        '5-5': KeuzelijstWaarde(invulwaarde='5-5',
                                label='5.5',
                                status='ingebruik',
                                definitie='5.5',
                                objectUri='https://wegenenverkeer.data.vlaanderen.be/id/concept/KlTakvrijeHoogte/5-5'),
        '6': KeuzelijstWaarde(invulwaarde='6',
                              label='6',
                              status='ingebruik',
                              definitie='6',
                              objectUri='https://wegenenverkeer.data.vlaanderen.be/id/concept/KlTakvrijeHoogte/6'),
        '6-5': KeuzelijstWaarde(invulwaarde='6-5',
                                label='6.5',
                                status='ingebruik',
                                definitie='6.5',
                                objectUri='https://wegenenverkeer.data.vlaanderen.be/id/concept/KlTakvrijeHoogte/6-5'),
        '7': KeuzelijstWaarde(invulwaarde='7',
                              label='7',
                              status='ingebruik',
                              definitie='7',
                              objectUri='https://wegenenverkeer.data.vlaanderen.be/id/concept/KlTakvrijeHoogte/7'),
        '7-5': KeuzelijstWaarde(invulwaarde='7-5',
                                label='7.5',
                                status='ingebruik',
                                definitie='7.5',
                                objectUri='https://wegenenverkeer.data.vlaanderen.be/id/concept/KlTakvrijeHoogte/7-5'),
        '8': KeuzelijstWaarde(invulwaarde='8',
                              label='8',
                              status='ingebruik',
                              definitie='8',
                              objectUri='https://wegenenverkeer.data.vlaanderen.be/id/concept/KlTakvrijeHoogte/8'),
        '8-5': KeuzelijstWaarde(invulwaarde='8-5',
                                label='8.5',
                                status='ingebruik',
                                definitie='8.5',
                                objectUri='https://wegenenverkeer.data.vlaanderen.be/id/concept/KlTakvrijeHoogte/8-5'),
        '9': KeuzelijstWaarde(invulwaarde='9',
                              label='9',
                              status='ingebruik',
                              definitie='9',
                              objectUri='https://wegenenverkeer.data.vlaanderen.be/id/concept/KlTakvrijeHoogte/9'),
        '9-5': KeuzelijstWaarde(invulwaarde='9-5',
                                label='9.5',
                                status='ingebruik',
                                definitie='9.5',
                                objectUri='https://wegenenverkeer.data.vlaanderen.be/id/concept/KlTakvrijeHoogte/9-5')
    }

    @classmethod
    def create_dummy_data(cls):
        return cls.create_dummy_data_keuzelijst(cls.options)

