name: Unittests
run-name: Unittests for ${{ github.sha }}
on: [push]

jobs:
  tests:
    name: Unittests across multiple Python versions and operating systems
    timeout-minutes: 10
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.9', '3.10', '3.11', '3.12', '3.13']
    steps:
      - uses: actions/checkout@v4
      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Installing requirements for running the tests
        run: uv pip install -r pyproject.toml --extra test
      - name: Run unittests with pytest
        run: python -m pytest -v
        working-directory: .
